WebApplication1/WebApplication1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Help;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AdminController : Controller
    {
        private projekatIEP db = new projekatIEP();

        // GET: Admin
        [AuthorizeAdmin]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin
        [AuthorizeAdmin]
        public ActionResult IndexPar()
        {
            return View(db.parametris.ToList());
        }

        // GET: Admin/Details/5
        [AuthorizeAdmin]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            parametri parametri = db.parametris.Find(id);
            if (parametri == null)
            {
                return HttpNotFound();
            }
            return View(parametri);
        }
        
        // GET: Admin/Edit/5
        [AuthorizeAdmin]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            parametri parametri = db.parametris.Find(id);
            if (parametri == null)
            {
                return HttpNotFound();
            }
            return View(parametri);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeAdmin]
        public ActionResult Edit([Bind(Include = "ID,N,D,S,G,P,C,T")] parametri model)
        {
            if (ModelState.IsValid)
            {
                parametri admin = db.parametris.FirstOrDefault();
                if (admin != null)
                {
                    if (!((model.S < model.G) && (model.G < model.P)))
                    {
                        ViewBag.Message = "Number of tokens must be in the following order: silver<gold<platinum.";
                        return View(model);
                    }

                    admin.N = model.N;
                    admin.D = model.D;
                    admin.S = model.S;
                    admin.G = model.G; 
                    admin.P = model.P;
                    admin.C = model.C; 
                    admin.T = model.T; 

                    db.Entry(admin).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("IndexPar");
                }
            }
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Controllers/TokenOrderController.cs
using Microsoft.AspNet.SignalR;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Help;
using WebApplication1.Hubs;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TokenOrderController : Controller
    {
        private projekatIEP db = new projekatIEP();

        // GET: TokenOrder
        [AuthorizeUser]
        public ActionResult Index()
        {
            return View();
        }

        // GET: TokenOrder/Details/5
        [AuthorizeUser]
        public ActionResult Details(int? page)
        {
            korisnik user = Session["User"] as korisnik;
            IList<narudzbina> orders = db.narudzbinas.Where(t => t.korisnik == user.UID).ToList();
            parametri admin = db.parametris.FirstOrDefault();

            int pageNumber = (page ?? 1);
            return View(PagedListExtensions.ToPagedList(orders, pageNumber, admin.N));
        }

        // GET: TokenOrder/Create
        [AuthorizeUser]
        public ActionResult Create()
        {
            parametri p = db.parametris.FirstOrDefault();
            return View(p);
        }

        // POST: TokenOrder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeUser]
        public ActionResult Create(string tokens)
        {
            narudzbina n = new narudzbina();
            n.GUID = Guid.NewGuid();

            parametri pom = db.parametris.FirstOrDefault();
            if (tokens == "silver") n.brTokena = pom.S;
            else
            if (tokens == "gold") n.brTokena = pom.G;
            else
            if (tokens == "platinum") n.brTokena = pom.P;
            else
            {
                ViewBag.Message = "0";
                return View();
            }


            korisnik k = Session["User"] as korisnik;
            n.korisnik = k.UID;

            n.cena = n.brTokena * pom.T;

            n.stanje = "Submitted";

            db.narudzbinas.Add(n);
            db.SaveChanges();
            return Redirect("http://stage.centili.com/payment/widget?apikey=e37b10434628c1a64bc981084cf4aa51&country=rs&reference=" + n.GUID);
            
        }

        [AuthorizeUser]
        public ActionResult Completed(Guid? reference, string status)
        {
            using (var transaction = db.Database.BeginTransaction(IsolationLevel.Serializable))
            {
                try
                {
                    narudzbina order = db.narudzbinas.Where(t => t.GUID == reference).FirstOrDefault();
                    if (order == null)
                        RedirectToAction("Details");
                    if (order.stanje == "Submitted")
                    {
                        if (status == "success")
                        {
                            order.stanje = "Completed";
                            korisnik user1 = Session["User"] as korisnik;
                            korisnik user = db.korisniks.Where(u => u.UID == user1.UID).FirstOrDefault();
                            user.brTokena += order.brTokena;
                            var number = user.brTokena;
                            db.Entry(user).State = EntityState.Modified;
                            db.Entry(order).State = EntityState.Modified;
                            db.SaveChanges();
                            SendEmail(user, "Token order", "Token order successfully completed!");
                            transaction.Commit();

                        }
                        else
                        {
                            order.stanje = "Canceled";
                            db.Entry(order).State = EntityState.Modified;
                            db.SaveChanges();
                            ViewBag.Mesage = "The order is canceled";
                            transaction.Commit();
                        }

                    }
                }
                catch (Exception e)
                {
                    transaction.Rollback();
                    ViewBag.Message = "There is an error in transaction";
                
                }
            }
            return RedirectToAction("Details");
        }

        [NonAction]
        public bool SendEmail(korisnik reciver, string subject, string emailBody)
        {
            try
            {
                string senderEmail = System.Configuration.ConfigurationManager.AppSettings["SenderEmail"].ToString();
                string senderPassword = System.Configuration.ConfigurationManager.AppSettings["SenderPassword"].ToString();

                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(senderEmail, senderPassword);
                MailMessage mailMessage = new MailMessage(senderEmail, reciver.mejl, subject, emailBody);
                mailMessage.IsBodyHtml = true;
                mailMessage.BodyEncoding = UTF8Encoding.UTF8;

                client.Send(mailMessage);

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/Admin/Details.cshtml
@model WebApplication1.Models.parametri

@{
    ViewBag.Title = "Parametars Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>parameters</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.N)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.N)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.D)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.D)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.S)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.S)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.G)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.G)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.P)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.T)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.T)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "IndexPar")
</p>

WebApplication1/WebApplication1/Views/Admin/Edit.cshtml
@model WebApplication1.Models.parametri

@{
    ViewBag.Title = "Edit Parameters";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if ((string)ViewBag.Message != null)
{
    <div class="row">
        <br />
        <div class="alert alert-warning" role="alert">
            <strong>@ViewBag.Message</strong>
        </div>
    </div>
}

<h2>Edit Parameters</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.N, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.N, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.N, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.D, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.D, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.D, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.G, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.G, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.G, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.C, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.C, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.C, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.T, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.T, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.T, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexPar")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin Home Page";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="jumbotron">
    <h1>Welcome admin!</h1>
    <p class="lead">
        @Html.ActionLink("Paramaters", "IndexPar", "Admin") |
        @Html.ActionLink("Moderate auctions", "NeedApproval", "Auction") |
        @Html.ActionLink("Enter", "IndexA", "Auction")|
        @Html.ActionLink("Buy tokens", "Index", "TokenOrder")|
        @Html.ActionLink("Edit admin info", "Details", "User")
    </p>
</div>

WebApplication1/WebApplication1/Views/Admin/IndexPar.cshtml
@model IEnumerable<WebApplication1.Models.parametri>

@{
    ViewBag.Title = "Admin Parameters";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Parameters</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.N)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.D)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.S)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.G)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.P)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.C)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.T)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.N)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.D)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.S)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.G)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.P)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.C)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.T)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) 
        </td>
    </tr>
}

</table>